/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.schedule;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Link {
	@JsonProperty("rel")
	private java.lang.String rel;

 	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Link [rel=").append(rel).append(", href=").append(href).append(", title=").append(title)
				.append("]");
		return builder.toString();
	}

	public void setRel(java.lang.String rel) {
		this.rel = rel;
	}

	public java.lang.String getRel() {
		return rel;
	}

	@JsonProperty("href")
	private java.lang.String href;

 	public void setHref(java.lang.String href) {
		this.href = href;
	}

	public java.lang.String getHref() {
		return href;
	}

	@JsonProperty("title")
	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

}