/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.schedule;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Room {
	@JsonProperty("capacity")
	private java.lang.Integer capacity;

 	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Room [capacity=").append(capacity).append(", id=").append(id).append(", name=").append(name)
				.append(", setup=").append(setup).append("]");
		return builder.toString();
	}

	public void setCapacity(java.lang.Integer capacity) {
		this.capacity = capacity;
	}

	public java.lang.Integer getCapacity() {
		return capacity;
	}

	@JsonProperty("id")
	private java.lang.String id;

 	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	@JsonProperty("setup")
	private java.lang.String setup;

 	public void setSetup(java.lang.String setup) {
		this.setup = setup;
	}

	public java.lang.String getSetup() {
		return setup;
	}

}