/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.schedule;

import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Slots {
	@JsonProperty("slots")
	private Slot[] slots;

 	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Slots [slots=").append(Arrays.toString(slots)).append("]");
		return builder.toString();
	}

	public void setSlots(Slot[] slots) {
		this.slots = slots;
	}

	public Slot[] getSlots() {
		return slots;
	}

}