/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.schedule;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Slot {
	@JsonProperty("slotId")
	private java.lang.String slotid;

 	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SlotElement [slotid=").append(slotid).append(", roomid=").append(roomid).append(", day=")
				.append(day).append(", roomcapacity=").append(roomcapacity).append(", fromtime=").append(fromtime)
				.append(", talk=").append(talk).append(", breakVar=").append(breakVar).append(", totime=")
				.append(totime).append(", fromtimemillis=").append(fromtimemillis).append(", totimemillis=")
				.append(totimemillis).append(", roomsetup=").append(roomsetup).append(", roomname=").append(roomname)
				.append(", notallocated=").append(notallocated).append("]");
		return builder.toString();
	}

	public void setSlotid(java.lang.String slotid) {
		this.slotid = slotid;
	}

	public java.lang.String getSlotid() {
		return slotid;
	}

	@JsonProperty("roomId")
	private java.lang.String roomid;

 	public void setRoomid(java.lang.String roomid) {
		this.roomid = roomid;
	}

	public java.lang.String getRoomid() {
		return roomid;
	}

	@JsonProperty("day")
	private java.lang.String day;

 	public void setDay(java.lang.String day) {
		this.day = day;
	}

	public java.lang.String getDay() {
		return day;
	}

	@JsonProperty("roomCapacity")
	private java.lang.Integer roomcapacity;

 	public void setRoomcapacity(java.lang.Integer roomcapacity) {
		this.roomcapacity = roomcapacity;
	}

	public java.lang.Integer getRoomcapacity() {
		return roomcapacity;
	}

	@JsonProperty("fromTime")
	private java.lang.String fromtime;

 	public void setFromtime(java.lang.String fromtime) {
		this.fromtime = fromtime;
	}

	public java.lang.String getFromtime() {
		return fromtime;
	}

	@JsonProperty("talk")
	private Talk talk;

 	public void setTalk(Talk talk) {
		this.talk = talk;
	}

	public Talk getTalk() {
		return talk;
	}

	@JsonProperty("break")
	private Break breakVar;

 	public void setBreakVar(Break breakVar) {
		this.breakVar = breakVar;
	}

	public Break getBreakVar() {
		return breakVar;
	}

	@JsonProperty("toTime")
	private java.lang.String totime;

 	public void setTotime(java.lang.String totime) {
		this.totime = totime;
	}

	public java.lang.String getTotime() {
		return totime;
	}

	@JsonProperty("fromTimeMillis")
	private java.lang.Long fromtimemillis;

 	public void setFromtimemillis(java.lang.Long fromtimemillis) {
		this.fromtimemillis = fromtimemillis;
	}

	public java.lang.Long getFromtimemillis() {
		return fromtimemillis;
	}

	@JsonProperty("toTimeMillis")
	private java.lang.Long totimemillis;

 	public void setTotimemillis(java.lang.Long totimemillis) {
		this.totimemillis = totimemillis;
	}

	public java.lang.Long getTotimemillis() {
		return totimemillis;
	}

	@JsonProperty("roomSetup")
	private java.lang.String roomsetup;

 	public void setRoomsetup(java.lang.String roomsetup) {
		this.roomsetup = roomsetup;
	}

	public java.lang.String getRoomsetup() {
		return roomsetup;
	}

	@JsonProperty("roomName")
	private java.lang.String roomname;

 	public void setRoomname(java.lang.String roomname) {
		this.roomname = roomname;
	}

	public java.lang.String getRoomname() {
		return roomname;
	}

	@JsonProperty("notAllocated")
	private java.lang.Boolean notallocated;

 	public void setNotallocated(java.lang.Boolean notallocated) {
		this.notallocated = notallocated;
	}

	public java.lang.Boolean getNotallocated() {
		return notallocated;
	}

}