/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.schedule;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Speaker {
	@JsonProperty("link")
	private Link link;

 	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SpeakerElement [link=").append(link).append(", name=").append(name).append("]");
		return builder.toString();
	}

	public void setLink(Link link) {
		this.link = link;
	}

	public Link getLink() {
		return link;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}