/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package eu.delucaconsulting.robot.rest.domain.voting;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Talk {
	@JsonProperty("sum")
	private java.lang.String sum;

 	public void setSum(java.lang.String sum) {
		this.sum = sum;
	}

	public java.lang.String getSum() {
		return sum;
	}

	@JsonProperty("track")
	private java.lang.String track;

 	public void setTrack(java.lang.String track) {
		this.track = track;
	}

	public java.lang.String getTrack() {
		return track;
	}

	@JsonProperty("speakers")
	private java.lang.String[] speakers;

 	public void setSpeakers(java.lang.String[] speakers) {
		this.speakers = speakers;
	}

	public java.lang.String[] getSpeakers() {
		return speakers;
	}

	@JsonProperty("avg")
	private java.lang.String avg;

 	public void setAvg(java.lang.String avg) {
		this.avg = avg;
	}

	public java.lang.String getAvg() {
		return avg;
	}

	@JsonProperty("type")
	private java.lang.String type;

 	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getType() {
		return type;
	}

	@JsonProperty("summary")
	private java.lang.String summary;

 	public void setSummary(java.lang.String summary) {
		this.summary = summary;
	}

	public java.lang.String getSummary() {
		return summary;
	}

	@JsonProperty("title")
	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	@JsonProperty("count")
	private java.lang.String count;

 	public void setCount(java.lang.String count) {
		this.count = count;
	}

	public java.lang.String getCount() {
		return count;
	}

	@JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}